export const formTemplates = {
  vehicles: [
    {
      name: "fuelType",
      type: "select",
      label: "Fuel Type",
      options: ["Petrol", "Diesel", "Electric", "Hybrid", "CNG"],
      required: true,
    },
    {
      name: "co2EmissionsPerKm",
      type: "number",
      label: "CO2 Emissions (g/km)",
      required: true,
      showIf: { fuelType: ["Petrol", "Diesel", "Hybrid"] },
    },
    {
      name: "engineSize",
      type: "number",
      label: "Engine Size (cc)",
      required: true,
      showIf: { fuelType: ["Petrol", "Diesel", "Hybrid"] },
    },
    {
      name: "batteryCapacity",
      type: "number",
      label: "Battery Capacity (kWh)",
      required: true,
      showIf: { fuelType: ["Electric", "Hybrid"] },
    },
    {
      name: "chargingTime",
      type: "number",
      label: "Charging Time (hours)",
      required: true,
      showIf: { fuelType: ["Electric", "Hybrid"] },
    },
    {
      name: "mileage",
      type: "number",
      label: "Current Mileage",
      required: true,
    },
    {
      name: "fuelEfficiency",
      type: "number",
      label: "Fuel Efficiency",
      required: true,
      showIf: { fuelType: ["Petrol", "Diesel", "Hybrid"] },
    },
  ],
  industrialEquipment: [
    {
      name: "powerSource",
      type: "select",
      label: "Power Source",
      options: ["Electric", "Diesel", "Gas", "Hybrid", "Pneumatic"],
      required: true,
    },
    {
      name: "powerRating",
      type: "number",
      label: "Power Rating (kW)",
      required: true,
    },
    {
      name: "energyEfficiencyRating",
      type: "select",
      label: "Energy Efficiency Rating",
      options: ["A+++", "A++", "A+", "A", "B", "C", "D"],
      required: true,
      showIf: { powerSource: ["Electric", "Hybrid"] },
    },
    {
      name: "energyConsumptionPerHour",
      type: "number",
      label: "Energy Consumption (kWh/hour)",
      required: true,
      showIf: { powerSource: ["Electric", "Hybrid"] },
    },
    {
      name: "fuelConsumptionPerHour",
      type: "number",
      label: "Fuel Consumption (L/hour)",
      required: true,
      showIf: { powerSource: ["Diesel", "Gas"] },
    },
    {
      name: "emissionStandard",
      type: "select",
      label: "Emission Standard",
      options: ["Stage V", "Stage IV", "Stage IIIB", "Stage IIIA"],
      required: true,
      showIf: { powerSource: ["Diesel", "Gas"] },
    },
    {
      name: "operatingHours",
      type: "number",
      label: "Daily Operating Hours",
      required: true,
    },
  ],
  buildingSystems: [
    {
      name: "systemType",
      type: "select",
      label: "System Type",
      options: ["HVAC", "Lighting", "Elevator", "Security"],
      required: true,
    },
    {
      name: "energyConsumption",
      type: "number",
      label: "Energy Consumption (kWh/day)",
      required: true,
    },
    {
      name: "energyEfficiencyRatio",
      type: "number",
      label: "Energy Efficiency Ratio",
      required: true,
    },
    {
      name: "refrigerantType",
      type: "select",
      label: "Refrigerant Type",
      options: ["R-410A", "R-32", "R-290", "None"],
      required: false,
      showIf: { systemType: ["HVAC"] },
    },
    {
      name: "lightingType",
      type: "select",
      label: "Lighting Type",
      options: ["LED", "Fluorescent", "Halogen", "Other"],
      required: true,
      showIf: { systemType: ["Lighting"] },
    },
  ],
  officeEquipment: [
    {
      name: "equipmentType",
      type: "select",
      label: "Equipment Type",
      options: ["Computer", "Printer", "Server", "Monitor", "Network Device"],
      required: true,
    },
    {
      name: "powerRating",
      type: "number",
      label: "Power Rating (W)",
      required: true,
    },
    {
      name: "standbyPower",
      type: "number",
      label: "Standby Power (W)",
      required: true,
    },
    {
      name: "energyLabel",
      type: "select",
      label: "Energy Label",
      options: ["A+++", "A++", "A+", "A", "B", "C"],
      required: true,
    },
    {
      name: "dailyUsageHours",
      type: "number",
      label: "Daily Usage Hours",
      required: true,
    },
    {
      name: "powerManagementEnabled",
      type: "boolean",
      label: "Power Management Enabled",
      required: true,
    },
  ],
};
