export const formTemplates = {
  vehicles: [
    {
      name: "fuelType",
      type: "select",
      label: "Fuel Type",
      options: ["Petrol", "Diesel", "Electric", "Hybrid"],
      required: true,
      placeholder: "Select fuel type",
    },
    {
      name: "engineSize",
      type: "number",
      label: "Engine Size (cc)",
      required: true,
      placeholder: "Enter engine size",
    },
    {
      name: "mileage",
      type: "number",
      label: "Current Mileage",
      required: true,
      placeholder: "Enter current mileage",
    },
    {
      name: "fuelEfficiency",
      type: "number",
      label: "Fuel Efficiency (km/l)",
      required: true,
      placeholder: "Enter fuel efficiency",
    },
  ],
  officeEquipment: [
    {
      name: "powerRating",
      type: "number",
      label: "Power Rating (W)",
      required: true,
      placeholder: "Enter power rating",
    },
    {
      name: "energyLabel",
      type: "select",
      label: "Energy Label",
      options: ["A+++", "A++", "A+", "A", "B", "C"],
      required: true,
      placeholder: "Select energy rating",
    },
    {
      name: "dailyUsageHours",
      type: "number",
      label: "Daily Usage Hours",
      required: true,
      placeholder: "Enter daily usage hours",
    },
  ],
  furniture: [
    {
      name: "material",
      type: "select",
      label: "Primary Material",
      options: ["Wood", "Metal", "Plastic", "Composite"],
      required: true,
      placeholder: "Select material",
    },
    {
      name: "recyclable",
      type: "boolean",
      label: "Recyclable",
      required: true,
    },
    {
      name: "ecoLabel",
      type: "text",
      label: "Eco Certification",
      placeholder: "Enter certification if any",
    },
  ],
  industrialEquipment: [
    {
      name: "powerSource",
      type: "select",
      label: "Power Source",
      options: ["Electric", "Diesel", "Gas", "Hybrid"],
      required: true,
      placeholder: "Select power source",
    },
    {
      name: "powerRating",
      type: "number",
      label: "Power Rating (kW)",
      required: true,
      placeholder: "Enter power rating",
    },
    {
      name: "operatingHours",
      type: "number",
      label: "Daily Operating Hours",
      required: true,
      placeholder: "Enter operating hours",
    },
  ],
  materialHandling: [
    {
      name: "liftCapacity",
      type: "number",
      label: "Lift Capacity (kg)",
      required: true,
      placeholder: "Enter lift capacity",
    },
    {
      name: "powerType",
      type: "select",
      label: "Power Type",
      options: ["Electric", "Manual", "Hydraulic"],
      required: true,
      placeholder: "Select power type",
    },
    {
      name: "batteryCapacity",
      type: "number",
      label: "Battery Capacity (Ah)",
      required: false,
      placeholder: "Enter battery capacity",
    },
  ],
  buildingSystems: [
    {
      name: "systemType",
      type: "select",
      label: "System Type",
      options: ["HVAC", "Lighting", "Elevator", "Security"],
      required: true,
      placeholder: "Select system type",
    },
    {
      name: "energyConsumption",
      type: "number",
      label: "Energy Consumption (kWh)",
      required: true,
      placeholder: "Enter energy consumption",
    },
    {
      name: "coverageArea",
      type: "number",
      label: "Coverage Area (sq m)",
      required: true,
      placeholder: "Enter coverage area",
    },
  ],
  itInfrastructure: [
    {
      name: "serverType",
      type: "select",
      label: "Server Type",
      options: ["Physical", "Virtual", "Hybrid"],
      required: true,
      placeholder: "Select server type",
    },
    {
      name: "powerUsage",
      type: "number",
      label: "Power Usage (W)",
      required: true,
      placeholder: "Enter power usage",
    },
    {
      name: "coolingRequirement",
      type: "number",
      label: "Cooling Requirement (BTU)",
      required: true,
      placeholder: "Enter cooling requirement",
    },
  ],
};
